# Generated by Django 4.2.13 on 2024-07-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_userorigin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userorigin",
            name="origin_id",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Origin ID"
            ),
            preserve_default=False,
        ),
    ]
