# Generated by Django 4.2.24 on 2025-10-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_userorigin_unique_user_per_data_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_api_use",
            field=models.DateField(
                blank=True, null=True, verbose_name="Latest API token usage date"
            ),
        ),
    ]
