# Generated by Django 5.2.12 on 2026-03-31 12:04

from django.db import migrations

import users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_user_last_api_use"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", users.models.CustomUserManager()),
            ],
        ),
    ]
