# Generated by Django 3.0.2 on 2020-03-11 14:47

import django.contrib.postgres.fields.ranges
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataSource",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
            ],
            options={
                "verbose_name": "Data source",
                "verbose_name_plural": "Data sources",
            },
        ),
        migrations.CreateModel(
            name="Target",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                (
                    "origin_id",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Origin ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Name"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "same_as",
                    models.URLField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Same object as",
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "last_modified_time",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("deleted", models.BooleanField(default=False)),
                (
                    "hours_updated",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "default_status",
                    models.IntegerField(
                        choices=[(0, "closed"), (1, "open"), (2, "undefined")],
                        default=2,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hours_target_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "data_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="provided_target_data",
                        to="hours.DataSource",
                    ),
                ),
                (
                    "last_modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hours_target_modified_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="first_children",
                        to="hours.Target",
                    ),
                ),
                (
                    "second_parent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="second_children",
                        to="hours.Target",
                    ),
                ),
            ],
            options={
                "verbose_name": "Target",
                "verbose_name_plural": "Targets",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Period",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                (
                    "origin_id",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Origin ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Name"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "same_as",
                    models.URLField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Same object as",
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "last_modified_time",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("deleted", models.BooleanField(default=False)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "closed"), (1, "open"), (2, "undefined")],
                        db_index=True,
                        default=1,
                    ),
                ),
                ("period", django.contrib.postgres.fields.ranges.DateRangeField()),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hours_period_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "data_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="provided_period_data",
                        to="hours.DataSource",
                    ),
                ),
                (
                    "last_modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hours_period_modified_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="periods",
                        to="hours.Target",
                    ),
                ),
            ],
            options={
                "verbose_name": "Period",
                "verbose_name_plural": "Periods",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Opening",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.IntegerField(
                        choices=[
                            (1, "Monday"),
                            (2, "Tuesday"),
                            (3, "Wednesday"),
                            (4, "Thursday"),
                            (5, "Friday"),
                            (6, "Saturday"),
                            (7, "Sunday"),
                        ]
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "closed"), (1, "open"), (2, "undefined")],
                        db_index=True,
                        default=1,
                    ),
                ),
                ("opens", models.TimeField(db_index=True)),
                ("closes", models.TimeField(db_index=True)),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                ("week", models.IntegerField(default=1, verbose_name="Week number")),
                ("month", models.IntegerField(default=0, verbose_name="Month number")),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="openings",
                        to="hours.Period",
                    ),
                ),
            ],
            options={
                "verbose_name": "Opening",
                "verbose_name_plural": "Openings",
            },
        ),
        migrations.CreateModel(
            name="Keyword",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                (
                    "origin_id",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Origin ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Name"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "same_as",
                    models.URLField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Same object as",
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "last_modified_time",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("deleted", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hours_keyword_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "data_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="provided_keyword_data",
                        to="hours.DataSource",
                    ),
                ),
                (
                    "last_modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hours_keyword_modified_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "targets",
                    models.ManyToManyField(
                        db_index=True, related_name="keywords", to="hours.Target"
                    ),
                ),
            ],
            options={
                "verbose_name": "Keyword",
                "verbose_name_plural": "Keywords",
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="target",
            constraint=models.UniqueConstraint(
                fields=("data_source", "origin_id"),
                name="hours_target_origin_id_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="period",
            index=django.contrib.postgres.indexes.GistIndex(
                fields=["period"], name="hours_perio_period_dce69b_gist"
            ),
        ),
        migrations.AddConstraint(
            model_name="period",
            constraint=models.UniqueConstraint(
                fields=("data_source", "origin_id"),
                name="hours_period_origin_id_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="keyword",
            constraint=models.UniqueConstraint(
                fields=("data_source", "origin_id"),
                name="hours_keyword_origin_id_unique",
            ),
        ),
    ]
