# Generated by Django 3.1.2 on 2020-10-26 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "django_orghierarchy",
            "0009_add_change_organization_regular_users_permission",
        ),
        ("hours", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalresource",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="django_orghierarchy.organization",
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="resources",
                to="django_orghierarchy.organization",
            ),
        ),
    ]
