# Generated by Django 3.1.2 on 2020-10-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hours", "0002_add_organization_to_resource"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalresource",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="resource",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
    ]
