# Generated by Django 3.0.2 on 2020-04-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0002_add_override_to_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='publication_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='period',
            name='publication_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='period',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='target',
            name='publication_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='target',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='target',
            name='target_type',
            field=models.IntegerField(choices=[(0, 'unit'), (1, 'unit_service'), (2, 'special_group'), (3, 'person'), (4, 'telephone'), (5, 'service'), (6, 'service_channel'), (7, 'service_at_unit'), (8, 'resource')], default=0),
        ),
        migrations.AlterField(
            model_name='opening',
            name='status',
            field=models.IntegerField(choices=[(0, 'closed'), (1, 'open'), (2, 'undefined'), (3, 'self_service'), (4, 'with_reservation'), (5, 'with key'), (6, 'only_entering'), (7, 'only_leaving')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='period',
            name='status',
            field=models.IntegerField(choices=[(0, 'closed'), (1, 'open'), (2, 'undefined'), (3, 'self_service'), (4, 'with_reservation'), (5, 'with key'), (6, 'only_entering'), (7, 'only_leaving')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='target',
            name='default_status',
            field=models.IntegerField(choices=[(0, 'closed'), (1, 'open'), (2, 'undefined'), (3, 'self_service'), (4, 'with_reservation'), (5, 'with key'), (6, 'only_entering'), (7, 'only_leaving')], default=2),
        ),
    ]
