# Generated by Django 3.0.2 on 2020-05-08 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0004_allow_null_opens_and_closes'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('opening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_hours', to='hours.Opening')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_hours', to='hours.Target')),
            ],
            options={
                'verbose_name': 'Daily hours',
                'verbose_name_plural': 'Daily hours',
            },
        ),
        migrations.AddConstraint(
            model_name='dailyhours',
            constraint=models.UniqueConstraint(fields=('target', 'date', 'opening'), name='unique_opening_per_date'),
        ),
    ]
