# Generated by Django 3.1.2 on 2020-11-19 06:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hours", "0004_allow_blank_name_in_resource"),
    ]

    operations = [
        migrations.CreateModel(
            name="SignedAuthEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("signature", models.TextField(verbose_name="Signature")),
                (
                    "created_at",
                    models.DateTimeField(verbose_name="Signature created at"),
                ),
                (
                    "valid_until",
                    models.DateTimeField(verbose_name="Signature valid until"),
                ),
                (
                    "invalidated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Invalidated time"
                    ),
                ),
            ],
            options={
                "verbose_name": "Signed auth entry",
                "verbose_name_plural": "Signed auth entries",
            },
        ),
    ]
