# Generated by Django 3.1.2 on 2020-11-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hours", "0006_add_period_origin"),
    ]

    operations = [
        migrations.AddField(
            model_name="dateperiod",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="historicaldateperiod",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
    ]
