# Generated by Django 3.0.7 on 2020-07-01 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "django_orghierarchy",
            "0009_add_change_organization_regular_users_permission",
        ),
        ("hours", "0006_add_fields_to_opening"),
    ]

    operations = [
        migrations.AddField(
            model_name="target",
            name="organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="targets",
                to="django_orghierarchy.Organization",
            ),
        ),
    ]
