# Generated by Django 3.1.2 on 2020-11-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hours", "0007_add_is_public_to_dateperiod"),
    ]

    operations = [
        migrations.AddField(
            model_name="timespangroup",
            name="is_removed",
            field=models.BooleanField(default=False),
        ),
    ]
