# Generated by Django 3.0.7 on 2020-07-02 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hours", "0008_fields_not_null"),
    ]

    operations = [
        migrations.CreateModel(
            name="TargetIdentifier",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "origin_id",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Origin ID"
                    ),
                ),
                (
                    "data_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identifiers",
                        to=settings.DJANGO_ORGHIERARCHY_DATASOURCE_MODEL,
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identifiers",
                        to="hours.Target",
                    ),
                ),
            ],
            options={
                "verbose_name": "Target identifier",
                "verbose_name_plural": "Target identifiers",
            },
        ),
        migrations.AddConstraint(
            model_name="targetidentifier",
            constraint=models.UniqueConstraint(
                fields=("data_source", "origin_id"),
                name="unique_identifier_per_data_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="targetidentifier",
            constraint=models.UniqueConstraint(
                fields=("data_source", "target"), name="unique_identifier_per_target"
            ),
        ),
    ]
