# Generated by Django 3.1.2 on 2020-11-26 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hours", "0008_add_soft_deletable_to_timespangroup"),
        ("hours", "0006_signedauthkey"),
    ]

    operations = []
