# Generated by Django 3.1.2 on 2020-12-07 09:29

import timezone_field.fields
from django.db import migrations

import hours.models


class Migration(migrations.Migration):
    dependencies = [
        ("hours", "0010_add_ancestry_fields_to_resource"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalresource",
            name="timezone",
            field=timezone_field.fields.TimeZoneField(
                blank=True,
                default=hours.models.get_resource_default_timezone,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="timezone",
            field=timezone_field.fields.TimeZoneField(
                blank=True,
                default=hours.models.get_resource_default_timezone,
                null=True,
            ),
        ),
    ]
