# Generated by Django 3.0.7 on 2020-09-25 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0010_add_address_to_target'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.TextField(choices=[('ADMIN', 'admin'), ('CITIZEN', 'citizen')], default='CITIZEN')),
                ('url', models.URLField(max_length=1000, unique=True, verbose_name='Link URL')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='hours.Target')),
            ],
            options={
                'verbose_name': 'Target link',
                'verbose_name_plural': 'Target links',
            },
        ),
    ]
