# Generated by Django 3.1.7 on 2021-03-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hours", "0012_add_end_time_on_next_day_to_timespan"),
    ]

    operations = [
        migrations.RenameField(
            model_name="datasource",
            old_name="user_editable",
            new_name="user_editable_organizations",
        ),
        migrations.RenameField(
            model_name="historicaldatasource",
            old_name="user_editable",
            new_name="user_editable_organizations",
        ),
        migrations.AddField(
            model_name="datasource",
            name="user_editable_resources",
            field=models.BooleanField(
                default=True, verbose_name="Resources may be edited by users"
            ),
        ),
        migrations.AddField(
            model_name="historicaldatasource",
            name="user_editable_resources",
            field=models.BooleanField(
                default=True, verbose_name="Resources may be edited by users"
            ),
        ),
    ]
