# Generated by Django 3.2.9 on 2021-11-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hours", "0016_add_date_periods_hash_to_resource"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalresource",
            name="date_periods_as_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resource",
            name="date_periods_as_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
