# Generated by Django 3.2.18 on 2024-03-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hours", "0017_add_date_periods_as_text_to_resource"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicaldatasource",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Data source",
                "verbose_name_plural": "historical Data sources",
            },
        ),
        migrations.AlterModelOptions(
            name="historicaldateperiod",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Period",
                "verbose_name_plural": "historical Periods",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalresource",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Resource",
                "verbose_name_plural": "historical Resources",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalrule",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Rule",
                "verbose_name_plural": "historical Rules",
            },
        ),
        migrations.AlterModelOptions(
            name="historicaltimespan",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Time span",
                "verbose_name_plural": "historical Time spans",
            },
        ),
        migrations.AlterField(
            model_name="historicaldatasource",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicaldateperiod",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalresource",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalrule",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicaltimespan",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
    ]
