# Generated by Django 5.2.11 on 2026-02-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hours", "0019_replace_enumfields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dateperiod",
            options={
                "ordering": [
                    models.OrderBy(models.F("order"), nulls_last=True),
                    "start_date",
                    "end_date",
                    "id",
                ],
                "verbose_name": "Period",
                "verbose_name_plural": "Periods",
            },
        ),
        migrations.AddField(
            model_name="dateperiod",
            name="order",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                help_text="Optional ordering value. When set, date periods with a lower order value appear first. Periods without an order value are sorted after those with one.",
                null=True,
                verbose_name="Order",
            ),
        ),
        migrations.AddField(
            model_name="historicaldateperiod",
            name="order",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                help_text="Optional ordering value. When set, date periods with a lower order value appear first. Periods without an order value are sorted after those with one.",
                null=True,
                verbose_name="Order",
            ),
        ),
    ]
