# Generated by Django 5.2.12 on 2026-03-25 04:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hours", "0020_add_order_to_dateperiod"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="periodorigin",
            name="unique_period_identifier_per_data_source",
        ),
        migrations.AddConstraint(
            model_name="periodorigin",
            constraint=models.UniqueConstraint(
                fields=("data_source", "origin_id", "period"),
                name="unique_period_origin_per_period",
            ),
        ),
    ]
